### ISSUE TITLE
accessing admin

### ISSUE THREAD

**Issue by balexandre** [heroku/heroku-buildpack-kong#11]
I read the documentation and the only part it could be something is in the configuration file, but it says it's **custom** so, it's something that we can live without changing ...

in Heroku, the `:80` represents Kong entry point, but what is the address to access the admin part of Kong? I other words, how do we setup Kong using its REST API interface?

or this is only possible through the configuration file? :(

**Comment by andjosh** [comment]
Following the steps in https://github.com/heroku/heroku-kong#admin-console, you can proxy the kong admin through kong itself and use the REST API interface to register APIs/plugins/etc.

**Comment by mars** [comment]
Thanks @andjosh, indeed we’ve taken great care to solve this problem already, all documented in README.
