### ISSUE TITLE
Including secret files needed by nginx

### ISSUE THREAD

**Issue by jcushman** [heroku/heroku-buildpack-kong#12]
Do you have any advice on the best way to provide secret files required by nginx? I'm particularly trying to provide the `client_ssl_cert_key` and `client_ssl_cert` needed for client-side authentication in `kong.conf.etlua`:

    #client_ssl_cert =               # If `client_ssl` is enabled, the absolute path
                                     # to the client SSL certificate for the
                                     # `proxy_ssl_certificate` directive. Note that
                                     # this value is statically defined on the node,
                                     # and currently cannot be configured on a
                                     # per-API basis.
    
    #client_ssl_cert_key =           # If `client_ssl` is enabled, the absolute path
                                     # to the client SSL key for the
                                     # `proxy_ssl_certificate_key` address. Note
                                     # this value is statically defined on the node,
                                     # and currently cannot be configured on a
                                     # per-API basis.

The simplest way would be to put the client SSL certificate and key files in git, but I don't want to include unencrypted secrets in my repository.

Alternatively I could provide a custom buildpack to write those files from environment variables, but that seems like a lot of custom work to get a setting to work.

Would it make sense to add a feature to this buildpack to write these nginx files from environment vars?

Or should there be a generic heroku-buildpack-env-to-file for cases like this?

Note that while I'm particularly interested in client auth, the same question might apply to `admin_ssl_cert_key`, `admin_ssl_cert`, `ssl_cert_key`, `ssl_cert`, and `lua_ssl_trusted_certificate` -- though I'm not sure if those all need to be secret or if that list is exhaustive.

Thanks!

**Comment by mars** [comment]
Hi @jcushman,

You can commit a [`.profile` script](https://devcenter.heroku.com/articles/dynos#the-profile-file) to a Heroku app to execute start-up tasks like this. Here's a simple `.profile` example of writing environment variable values into files:

```bash
ENV_DIR=tmp/env/

mkdir -p $ENV_DIR

echo "$KONG_CLIENT_SSL_CERT" > $ENV_DIR/KONG_CLIENT_SSL_CERT
echo "$KONG_CLIENT_SSL_CERT_KEY" > $ENV_DIR/KONG_CLIENT_SSL_CERT_KEY
```

…and then configure Kong to read those files via `kong.conf.etlua`:

```
client_ssl_cert = tmp/env/KONG_CLIENT_SSL_CERT
client_ssl_cert_key = tmp/env/KONG_CLIENT_SSL_CERT_KEY
```

**Comment by jcushman** [comment]
Thanks! Fast response, much appreciated.
