### ISSUE TITLE
Use with heroku private spaces DNS Service Discovery

### ISSUE THREAD

**Issue by brandoshmando** [heroku/heroku-buildpack-kong#13]
Hi there,

I'm having some trouble wrapping my head around which ports are usable for this buildpack. I've done some rooting around in the source and noticed that by using the `KONG_EXPOSE` env var, we can specify the listener that binds to the heroku internal `PORT` env var. In doing so, the listeners for all of the other types are set to their [default values](https://github.com/heroku/heroku-buildpack-kong/blob/master/config/kong-12f.lua#L21). However, I've noticed that none of these defaulted ports seem to actually be open. For instance, when trying the following commands in a bash shell for my app which is in a private space ([DNS lookup docs here](https://devcenter.heroku.com/articles/dyno-dns-service-discovery#usage)), I get connection refused errors:

```
$ curl http(s)://localhost:8443
curl: (7) Failed to connect to localhost port 8443: Connection refused

# via DNS lookup per docs
$ curl http(s)://web.app-name.app.localspace:8443
curl: (7) Failed to connect to localhost port 8443: Connection refused
```

The confusing part about this is that when I do the same using the value from the `PORT` env var, I get the same error, but when I use the proxy_port returned by the config endpoint of kong, it seems to work fine.

I have a couple of questions related to this:

1) Are we only able to open up one port per app using this buildpack? What I mean is, if I wanted to have one proxy listener and one proxy ssl listener, would I need two separate heroku apps using this buildpack, one app with the `KONG_EXPOSE` var set to `proxy` and the other app set to `proxyssl`? Both of these apps would be sharing the same DB.
2) Per the Heroku DNS docs:

> To communicate via the private network, your process needs to bind to its dyno’s private IP address on a port between 1024 and 65535.

So my assumption was that because the [default ports specified in kong-12f.lua](https://github.com/heroku/heroku-buildpack-kong/blob/master/config/kong-12f.lua#L21) are within the allowed range, that they would be available via the DNS lookup syntax within the private network. However, that assumption seems to be wrong. Is there something I'm missing here or did I just misinterpret how this buildpack exposes ports?

To give you some context on our use case, we want to have a proxy ssl listener exposed to incoming traffic using the `PORT` env var, but we also want a proxy http listener that is available within the private network of our private space. In order to do this, would the following be the best way to go about it.

a) Create one app exposing the service as proxyssl using the the `KONG_EXPOSE` env var.
b) Create a second app that exposes the service as a plain old http proxy _but_ add some code that would get an env var where we could specify the port that it is listening on, within the allowed range per the Heroku DNS docs.
c) Both apps share the same DB

Let me know your thoughts when you have a minute. I'm happy to submit a PR with any necessary code/documentation updates, but I wanted to get some input before I got started. Thanks!

__Edit__: If there's any way to do this using a single app that would be preferable, I just didn't see any good way of doing it since the sample heroku app doesn't have a procfile and relies on `nginx` command to start the process.

**Comment by brandoshmando** [comment]
To follow up on this, the issue that I was running into was based on a misinterpretation of Heroku's private space DNS docs:

> A process type of any kind (web or worker) can choose to listen on any available port, and other dynos in the space can connect to that port on the dyno host.

My thought was that we could disregard the `$PORT` env var completely and let Kong listen on a port of our choosing. Instead, any web process _still needs to bind to the `$PORT` env_, but any sub-process on the web process _or_ worker process can listen on a port of their choosing. That led me to the issue of somehow specifying a port for Kong to listen on that would be on non-web processes. I've opened #15 with changes that will address this use case including documentation.

**Comment by mars** [comment]
Glad to hear to found a way forward with this issue. Thanks for following-up!
