### ISSUE TITLE
Detection failure

### ISSUE THREAD

**Issue by cyrilchapon** [heroku/heroku-buildpack-kong#16]
When Running example

> Create a new git repo and Heroku app:

```
mkdir my-kong-app
cd my-kong-app
git init
heroku create $APP_NAME
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-kong
heroku addons:create heroku-postgresql:hobby-dev
```

> Create the file config/kong.conf.etlua based on the sample config file. This is a config template which generates config/kong.conf at runtime.

```
git add config/kong.conf.etlua
git commit -m '🐒'
git push heroku master
```

Leads to 
```
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (4/4), 6.65 KiB | 6.65 MiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-kong
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to guarded-coast-23308.
remote: 
To https://git.heroku.com/guarded-coast-23308.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/guarded-coast-23308.git'
```

**Comment by cyrilchapon** [comment]
And of course,

```
git clone https://git.heroku.com/guarded-coast-23308.git
```

lead to an empty directory

**Comment by cyrilchapon** [comment]
Manualy creating app on heroku, pushing to a separate repo, binding heroku to github and deploying through github leads to the same

**Comment by mars** [comment]
Sounds like you set it up correctly, but something is clearly missing.

There’s a reference/example app you can try too, perhaps examining it will help you find the missing piece:

https://github.com/heroku/heroku-kong

**Comment by cyrilchapon** [comment]
When trying to override `detect` script with something like [null buildpack one](https://github.com/ryandotsmith/null-buildpack/blob/master/bin/detect), it throws on `release` cycle phase with something like :

> missing app/config/kong.conf.etlua

Haven't read the code further but I guess during `compile` phase, it copies from config/kong.conf.etlua to app/config/kong.conf.etlua. So it realy seems like in both `compile` and `detect` scripts, pushed kong.conf.etlua is somehow not "visible" oO

**Comment by mars** [comment]
Thanks for the bug reproduction @loicpirez and persistence here @cyrilchapon  🙏 😊  

I've now reproduced this behavior too, and am addressing with Heroku build & languages.

**Comment by mars** [comment]
This seems to happen when the only file in the repo is `config/kong.conf.etlua`.

If you commit a file at the top-level, like for example a `README.md`, then the build will proceed without this error.

I will continue to address this with the Heroku build folks, but at least we know how to workaround this issue.
